
/**************************************************************
 *	
 *	collect, 8 bit, 11025Hz,
 *	1 channel, 1588 bytes/channel
 *	Total Size: 1 * 1588 + 4 (header) = 1632 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/kateshambaugh/Documents/MediaDevArch/FinalProject/Final/collect.wav
 *	Time-stamp: Tue Apr 23 11:50:41 2019
 *	
 **************************************************************/

#ifndef __COLLECTH__
#define __COLLECTH__

#define COLLECTFREQ 11025
#define COLLECTLEN 1588

extern const unsigned char collect[1588];

#endif /* __COLLECTH__ */
