
/**************************************************************
 *	
 *	gameSong, 8 bit, 11025Hz,
 *	1 channel, 1867129 bytes/channel
 *	Total Size: 1 * 1867129 + 4 (header) = 1867173 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/kateshambaugh/Documents/MediaDevArch/FinalProject/M04/gameSong.wav
 *	Time-stamp: Tue Apr 23 10:39:32 2019
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 1867129

extern const unsigned char gameSong[1867129];

#endif /* __GAMESONGH__ */
