
/**************************************************************
 *	
 *	heavenSong, 8 bit, 11025Hz,
 *	1 channel, 670831 bytes/channel
 *	Total Size: 1 * 670831 + 4 (header) = 670875 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/kateshambaugh/Documents/MediaDevArch/FinalProject/M04/heavenSong.wav
 *	Time-stamp: Tue Apr 23 11:13:38 2019
 *	
 **************************************************************/

#ifndef __HEAVENSONGH__
#define __HEAVENSONGH__

#define HEAVENSONGFREQ 11025
#define HEAVENSONGLEN 670831

extern const unsigned char heavenSong[670831];

#endif /* __HEAVENSONGH__ */
