
/**************************************************************
 *	
 *	hellSong, 8 bit, 11025Hz,
 *	1 channel, 335805 bytes/channel
 *	Total Size: 1 * 335805 + 4 (header) = 335849 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/kateshambaugh/Documents/MediaDevArch/FinalProject/M04/hellSong.wav
 *	Time-stamp: Tue Apr 23 10:44:51 2019
 *	
 **************************************************************/

#ifndef __HELLSONGH__
#define __HELLSONGH__

#define HELLSONGFREQ 11025
#define HELLSONGLEN 335805

extern const unsigned char hellSong[335805];

#endif /* __HELLSONGH__ */
