
/**************************************************************
 *	
 *	purgatorySong, 8 bit, 11025Hz,
 *	1 channel, 635914 bytes/channel
 *	Total Size: 1 * 635914 + 4 (header) = 635958 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/kateshambaugh/Documents/MediaDevArch/FinalProject/M04/purgatorySong.wav
 *	Time-stamp: Tue Apr 23 11:05:15 2019
 *	
 **************************************************************/

#ifndef __PURGATORYSONGH__
#define __PURGATORYSONGH__

#define PURGATORYSONGFREQ 11025
#define PURGATORYSONGLEN 635914

extern const unsigned char purgatorySong[635914];

#endif /* __PURGATORYSONGH__ */
