
/**************************************************************
 *	
 *	sword, 8 bit, 11025Hz,
 *	1 channel, 5991 bytes/channel
 *	Total Size: 1 * 5991 + 4 (header) = 6035 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/kateshambaugh/Documents/MediaDevArch/FinalProject/Final/sword.wav
 *	Time-stamp: Tue Apr 23 12:02:34 2019
 *	
 **************************************************************/

#ifndef __SWORDH__
#define __SWORDH__

#define SWORDFREQ 11025
#define SWORDLEN 5991

extern const unsigned char sword[5991];

#endif /* __SWORDH__ */
