
/**************************************************************
 *	
 *	titleSong, 8 bit, 11025Hz,
 *	1 channel, 627411 bytes/channel
 *	Total Size: 1 * 627411 + 4 (header) = 627455 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/kateshambaugh/Documents/MediaDevArch/FinalProject/M04/titleSong.wav
 *	Time-stamp: Tue Apr 23 10:32:16 2019
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 627411

extern const unsigned char titleSong[627411];

#endif /* __TITLESONGH__ */
